version: '3.8'

services:
  whisper-service:
    build: 
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python-service:/app
    environment:
      - FLASK_ENV=development

  springboot-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - whisper-service
    environment:
      - WHISPER_SERVICE_URL=http://whisper-service:5000 